### PR TITLE
Basic Windows support

### PR DESCRIPTION
**Pull request by kirbyfan64**
Not sure if Windows is technically supposed to be supported...

...but these resolves the issue @apense pointed out in #13.

### CODE REVIEW

**Comment by apense** [comment]
My Mingw64 install is working well :smile: . It's much easier to use than raw ``sdl2``, and since the ``graphics`` module doesn't work with ``sdl2`` yet, this is a great option.

**Comment by yglukhov** [comment]
Does this fix work with both mingw and bare win32?

**Comment by kirbyfan64** [comment]
No clue. I don't use Windows. I just opened up 20 MSDN pages to figure out what to do. :)

**Comment by yglukhov** [comment]
@apense, could you verify this please? ;) I suspect this fix might break mingw.

**Comment by apense** [comment]
Actually, it doesn't seem to be doing anything. Is this still under ``when not defined(windows)``? That's true on MinGW, too (which is what I use).

**Comment by yglukhov** [comment]
So the proper fix for windows would be not using --noMain flag when compiling. `naketools.nim` in nimx already does that, so i'm closing this.

**Pull request closed without merging**
